language: php

dist: trusty
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

  include:
    - php: 5.3
      dist: precise

install:
  - travis_wait composer install --no-interaction
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then
      export PHP_CS_FIXER="./dev-tools/vendor/bin/php-cs-fixer";
      export RUN_CS_FIXER="true";
    fi
  - cd dev-tools; composer update; cd ..

before_script:
  - vendor/bin/phpunit-4.8-fixer

script:
  - vendor/bin/phpunit

after_script:
  - travis_retry bin/coveralls.sh
